- name: Print the args
  debug:
    msg:
      - "{{ rm_swagger_json }}"
      - "{{ api_object_path}}"
      - "{{ module_name }}"
      - "{{ module_version }}"
      - "{{ collection_name }}"
      - "{{ author }}"

- name: Get the CURRENT WORKING DIR
  command: "pwd"
  register: dir

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tmp_directory

- name: EXECUTE the python script
  command: python3 doc_generator.py "{{ rm_swagger_json }}" "{{ api_object_path }}" "{{ module_name }}" "{{ module_version }}" "{{ resource }}" "{{ collection_org }}" "{{ collection_name }}" "{{ unique_key }}" "{{ author }}" "{{ tmp_directory["path"] }}"
  args:
    chdir: "{{ dir['stdout'] }}/security_rm_builder/roles/scaffold_resource_module/templates"
  delegate_to: 127.0.0.1
  run_once: true

- name: Display multiple file contents
  debug: var=item
  with_file:
    - "{{ tmp_directory['path'] }}/data.yml"
    - "{{ tmp_directory['path'] }}/params.json"
  register: test

- name: Copy the MODULE DOC
  copy: content="{{ test['results'][0]['item'] }}" dest="{{ dir['stdout'] }}/security_rm_builder/roles/init/vars/data.yaml"

- name: Copy the MODULE PARAM DICT
  copy: content="{{ test['results'][1]['item'] }}" dest="{{ dir['stdout'] }}/security_rm_builder/roles/init/vars/module_params_dict.json"

- name: Extract DOCUMENTATION from source (for new module)
  set_fact:
    rm_documentation: "{{ test['results'][0]['item'] }}"
  when: test is defined

- name: Extract MODULE PARAMS Dict from source (for new module)
  set_fact:
    module_params_dict: "{{ test['results'][1]['item'] }}"
  when: test is defined

- name: get the API object
  set_fact:
    api_object: "api/{{ api_object_path.split('/')[1] | default('default') }}"

- name: Template each of the files
  include: template.yaml
  with_items: "{{ resource_module_templates }}"
  loop_control:
    loop_var: template

- name: Delete TEMP data files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ dir['stdout'] }}/security_rm_builder/roles/init/vars/data.yaml"
    - "{{ dir['stdout'] }}/security_rm_builder/roles/init/vars/module_params_dict.json"