---
authors:
    - Ansible Security Community (ansible-security)
license_file: LICENSE
dependencies:
    "ansible.netcommon": "*"
name: security_rm_builder
namespace: ansible_security
readme: README.md
repository: https://github.com/ansible-security/security_rm_builder
version: 0.0.1
